{"raw":{},"required":["Filename","Size"],"package":"python3-zope.exceptions","source":"zope.exceptions","version":"4.0.8-1","section":"zope","priority":"optional","architecture":"all","depends":["python3-pkg-resources","python3-zope.interface","python3:any (>= 3.3.2-2~)"],"installedSize":90,"maintainer":"Debian/Ubuntu Zope Team <pkg-zope-developers@lists.alioth.debian.org>","description":"Zope exceptions for Python 3","homepage":"http://pypi.python.org/pypi/zope.exceptions","filename":"pool/main/z/zope.exceptions/python3-zope.exceptions_4.0.8-1_all.deb","size":16756,"md5":"3ccf8d3724b331320b1e1f6c360d23be","sha256":"d02616488ab022872075cd3dfdd70e674d0d968a1daf6da0b8958c259e9471c9","descriptionMd5":"6659ed22b4d66ce3d4e50aa50de55f19"}