{"raw":{},"required":["Filename","Size"],"package":"python3-django-dbconn-retry","source":"python-django-dbconn-retry","version":"0.1.5-1","section":"python","priority":"optional","architecture":"all","depends":["python3-django","python3:any (>= 3.3.2-2~)"],"installedSize":37,"maintainer":"Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>","description":"reconnect on a failed database (Python3 version)","homepage":"https://github.com/jdelic/django-dbconn-retry/","filename":"pool/main/p/python-django-dbconn-retry/python3-django-dbconn-retry_0.1.5-1_all.deb","size":8528,"md5":"52b748c97351e90482f3ab815cb81268","sha256":"aeb1f2c322079232b58cc5284a477144410a6c92453083e262d7301122c13ec9","descriptionMd5":"e6f9867f49ff9821aa4e414064f0370a"}