{"raw":{},"required":["Filename","Size"],"package":"python-zope.exceptions","source":"zope.exceptions","version":"4.0.8-1","section":"python","priority":"optional","architecture":"all","depends":["python-pkg-resources","python-zope.interface","python:any (<< 2.8)","python:any (>= 2.7.5-5~)"],"installedSize":93,"maintainer":"Debian/Ubuntu Zope Team <pkg-zope-developers@lists.alioth.debian.org>","description":"Zope exceptions for Python","homepage":"http://pypi.python.org/pypi/zope.exceptions","filename":"pool/main/z/zope.exceptions/python-zope.exceptions_4.0.8-1_all.deb","size":16712,"md5":"230306973ed1d96fa4a9167616925628","sha256":"0257f515083589b1cd3640347126ae2d29ff9c93e89cc2032315e151e27581fd","descriptionMd5":"fb63650b0843d0f5986f71aa80d2082d"}