{"raw":{},"required":["Filename","Size"],"package":"python3-django-dbconn-retry","source":"python-django-dbconn-retry","version":"0.1.7-1","section":"python","priority":"optional","architecture":"all","depends":["python3-django","python3:any"],"installedSize":37,"maintainer":"Debian Python Team <team+python@tracker.debian.org>","description":"reconnect on a failed database (Python3 version)","homepage":"https://github.com/jdelic/django-dbconn-retry/","filename":"pool/main/p/python-django-dbconn-retry/python3-django-dbconn-retry_0.1.7-1_all.deb","size":9216,"md5":"8c22f61dbc50bd7c3c8fc3189b8efd20","sha256":"5257c6fc2a8f6157bd14a262af25303c27fb3de4582bf30e1231eb5acfd3a32f","descriptionMd5":"e6f9867f49ff9821aa4e414064f0370a"}