{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-django-dbconn-retry",
	"source": "python-django-dbconn-retry",
	"version": "0.1.9-1",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-django",
		"python3:any"
	],
	"installedSize": 39,
	"maintainer": "Debian Python Team <team+python@tracker.debian.org>",
	"description": "reconnect on a failed database (Python3 version)",
	"homepage": "https://github.com/jdelic/django-dbconn-retry/",
	"filename": "pool/main/p/python-django-dbconn-retry/python3-django-dbconn-retry_0.1.9-1_all.deb",
	"size": 9876,
	"md5": "0dd0c0804e54a9987aa6b5dcf2df2ae8",
	"sha256": "b749610fc4f47ccb581e829d06ac6aefc9b32a66544f6c680c03285413d1628d",
	"descriptionMd5": "e6f9867f49ff9821aa4e414064f0370a"
}