[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-exceptiongroup",
	"source": "python-exceptiongroup",
	"version": "1.1.0-1",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3:any"
	],
	"breaks": [
		"python3-trio (<< 0.22)"
	],
	"installedSize": 65,
	"maintainer": "Debian Python Team <team+python@tracker.debian.org>",
	"description": "Backport of PEP 654 (exception groups)",
	"homepage": "https://github.com/agronholm/exceptiongroup/",
	"filename": "pool/main/p/python-exceptiongroup/python3-exceptiongroup_1.1.0-1_all.deb",
	"size": 17412,
	"md5": "1e9a4a00f1bacb38704be0ef776df324",
	"sha256": "5cd8098bad1c6127270d8bfd7fe598b33faf622d820a298195c8f0bdf498a8e3",
	"descriptionMd5": "c0b3bacd074a82b7b90b912e5c5135a1"
}]