[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-django-dbconn-retry",
	"source": "python-django-dbconn-retry",
	"version": "0.1.5-1.1",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-django",
		"python3:any"
	],
	"installedSize": 37,
	"maintainer": "Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>",
	"description": "reconnect on a failed database (Python3 version)",
	"homepage": "https://github.com/jdelic/django-dbconn-retry/",
	"filename": "pool/main/p/python-django-dbconn-retry/python3-django-dbconn-retry_0.1.5-1.1_all.deb",
	"size": 8672,
	"md5": "4412a1d449653a4c270a5487180788fe",
	"sha256": "92b2f7b1f4273998f1d700b9c508b65250a4c6793182db63b60604c29e634154",
	"descriptionMd5": "e6f9867f49ff9821aa4e414064f0370a"
}]