{"raw":{},"required":["Filename","Size"],"package":"python3-zope.exceptions","source":"zope.exceptions","version":"5.0.1-2","section":"zope","priority":"optional","architecture":"all","depends":["python3-pkg-resources","python3-zope.interface","python3:any"],"installedSize":96,"maintainer":"Debian QA Group <packages@qa.debian.org>","description":"Zope exceptions for Python 3","homepage":"https://github.com/zopefoundation/zope.exceptions","filename":"pool/main/z/zope.exceptions/python3-zope.exceptions_5.0.1-2_all.deb","size":18104,"md5":"741ec078bfb567510e0a45b98d8ba197","sha256":"23debebd16eab694be3a92a44b5e38bd75d20b4f3c98dbc8fd79905c7ee3dea4","descriptionMd5":"6659ed22b4d66ce3d4e50aa50de55f19"}