[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-django-dbconn-retry",
	"source": "python-django-dbconn-retry",
	"version": "0.1.8-1",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-django",
		"python3:any"
	],
	"installedSize": 37,
	"maintainer": "Debian Python Team <team+python@tracker.debian.org>",
	"description": "reconnect on a failed database (Python3 version)",
	"homepage": "https://github.com/jdelic/django-dbconn-retry/",
	"filename": "pool/main/p/python-django-dbconn-retry/python3-django-dbconn-retry_0.1.8-1_all.deb",
	"size": 9272,
	"md5": "2ecd4ba9a2136ece29684490ed36eb36",
	"sha256": "2c5b57081a0e1a9e40c09dceb022451137a04cf2c95827e17499713851f1c3f9",
	"descriptionMd5": "e6f9867f49ff9821aa4e414064f0370a"
}]